## This function cleans the High School Names to match them with SAT/AP data.
## Source : Gadoe [Data Reports] (https://app3.doe.k12.ga.us/ows-bin/owa/fte_pack_enrollgrade.entry_form) 

schoolNameCleanup <- function(df) {
			df[df$Col2=="110985",]$High.School<-"Phoenix High School -Whitefield"
			df[df$Col2=="112277",]$High.School<-"Phoenix High School -Gwinnett"
			df[df$Col2=="110281",]$High.School<-"Johnson Magnet"
			df[df$Col2=="110275",]$High.School<-"Academy of Richmond County High School"
			df[df$Col2=="111998",]$High.School<-"Pope High School"
			df[df$Col2=="112670",]$High.School<-"Beach High School"
			df[df$Col2=="110065",]$High.School<-"Americus Sumter County High South"
			df[df$Col2=="111868",]$High.School<-"Arabia Mountain High School - Academy of Engineering, Medicine and Environm"
			df[df$Col2=="110235",]$High.School<-"Mays High School"
			df[df$Col2=="112230",]$High.School<-"Berrien High School"
			df[df$Col2=="110111",]$High.School<-"The Best Academy at Benjamin S. Carson High School"
			df[df$Col2=="110269",]$High.School<-"Booker T. Washington High School - Health, Sciences and Nutrition Small Sch"
			df[df$Col2=="110112",]$High.School<-"Booker T. Washington - Early College Small School"
			df[df$Col2=="111615",]$High.School<-"Bradwell Institute"
			df[df$Col2=="111992",]$High.School<-"Kell High School"
			df[df$Col2=="110263",]$High.School<-"Early College High School at Carver"
			df[df$Col2=="110418",]$High.School<-"School of Health Sciences and Research at Carver"
			df[df$Col2=="110238",]$High.School<-"School of Technology at Carver"
			df[df$Col2=="110212",]$High.School<-"The School of the Arts at Carver"
			df[df$Col2=="110625",]$High.School<-"Cass High School"
			df[df$Col2=="110650",]$High.School<-"Chamblee Charter High School"
			df[df$Col2=="112534",]$High.School<-"Charles R. Drew High School"
			df[df$Col2=="112802",]$High.School<-"Charter Conservatory for Liberal Arts & Technology"
			df[df$Col2=="111100",]$High.School<-"Coffee High School"
			df[df$Col2=="110143",]$High.School<-"Coretta Scott King Young Women's Academy High School"
			df[df$Col2=="110209",]$High.School<-"Therrell School of Health and Science"
			df[df$Col2=="111035",]$High.School<-"Dawson County High School"
			df[df$Col2=="112720",]$High.School<-"DeKalb Alternative School"
			df[df$Col2=="111053",]$High.School<-"Dekalb Early College Academy"
			df[df$Col2=="111224",]$High.School<-"Destiny Achievers Academy of Excellence"
			df[df$Col2=="111124",]$High.School<-"Dublin High SChool"
			df[df$Col2=="111551",]$High.School<-"Dutchtown High"
			df[df$Col2=="112038",]$High.School<-"Eagle's Landing High School"
			df[df$Col2=="110814",]$High.School<-"Early College Academy of Columbus"
			df[df$Col2=="111210",]$High.School<-"Elbert County High School"
			df[df$Col2=="111722",]$High.School<-"Elite Scholars Academy School"
			df[df$Col2=="110395",]$High.School<-"Fannin County High School"
			df[df$Col2=="111281",]$High.School<-"Flowery Branch High"
			df[df$Col2=="110164",]$High.School<-"Douglass High School"
			df[df$Col2=="110069",]$High.School<-"Fulton Science Academy High School"
			df[df$Col2=="111435",]$High.School<-"Glascock County Consolidated School"
			df[df$Col2=="110675",]$High.School<-"Gordon Lee High School"
			df[df$Col2=="111140",]$High.School<-"Gwinnett School of Mathematics, Science and Technology"
			df[df$Col2=="113068",]$High.School<-"Hapeville Charter Career Academy"
			df[df$Col2=="111350",]$High.School<-"Heard County High School"
			df[df$Col2=="110170",]$High.School<-"Grady High School"
			df[df$Col2=="112682",]$High.School<-"Jenkins High School"
			df[df$Col2=="110061",]$High.School<-"Independence Alternative School"
			df[df$Col2=="110425",]$High.School<-"Jackson County High School"
			df[df$Col2=="110294",]$High.School<-"Davidson Magnet School"
			df[df$Col2=="113320",]$High.School<-"Johnson County High School"
			df[df$Col2=="111836",]$High.School<-"Lithia Springs Comprehensive High School"
			df[df$Col2=="111869",]$High.School<-"Locust Grove High"
			df[df$Col2=="110295",]$High.School<-"Laney High School"
			df[df$Col2=="111990",]$High.School<-"Marietta High School" 
			df[df$Col2=="110495",]$High.School<-"Marion County Middle/High School"
			df[df$Col2=="111843",]$High.School<-"Martin Luther King, Jr. High School"
			df[df$Col2=="110180",]$High.School<-"Maynard H. Jackson, Jr. High School"
			df[df$Col2=="112080",]$High.School<-"Metter High School" 
			df[df$Col2=="112725",]$High.School<-"Model High"
			df[df$Col2=="110045",]$High.School<-"Monroe High School"
			df[df$Col2=="112200",]$High.School<-"Montgomery Co. High"
			df[df$Col2=="110991",]$High.School<-"Morris Innovative High School"
			df[df$Col2=="110378",]$High.School<-"Mountain Education Center School"
			df[df$Col2=="111729",]$High.School<-"Mundy's Mill High School"
			df[df$Col2=="110800",]$High.School<-"North Clayton High School"
			df[df$Col2=="111154",]$High.School<-"North Springs High School"
			df[df$Col2=="111945",]$High.School<-"Northeast High School"
			df[df$Col2=="111695",]$High.School<-"Pickens County High School"
			df[df$Col2=="112430",]$High.School<-"Portal Middle/High School"
			df[df$Col2=="110710",]$High.School<-"Rabun County High School"
			df[df$Col2=="110940",]$High.School<-"Randolph Clay High School"
			df[df$Col2=="112000",]$High.School<-"Osborne High School"
			df[df$Col2=="111104",]$High.School<-"Alexander High School"
			df[df$Col2=="112680",]$High.School<-"Groves High School"
			df[df$Col2=="111409",]$High.School<-"Early College Program"
			df[df$Col2=="112710",]$High.School<-"The School of Liberal Studies at Savannah High"
			df[df$Col2=="111227",]$High.School<-"Schley Middle High School"
			df[df$Col2=="111090",]$High.School<-"Seminole County Middle/High School"
			df[df$Col2=="112714",]$High.School<-"Johnson High School"
			df[df$Col2=="110211",]$High.School<-"South Atlanta Law and Social Justice School"
			df[df$Col2=="110460",]$High.School<-"Southeast Bulloch High School"
			df[df$Col2=="111048",]$High.School<-"Southwest DeKalb High School"
			df[df$Col2=="111277",]$High.School<-"Starrs Mill High School"
			df[df$Col2=="110300",]$High.School<-"Josey High School"
			df[df$Col2=="111030",]$High.School<-"Terrell High School"
			df[df$Col2=="110339",]$High.School<-"Therrell School of Law, Government and Public Policy"
			df[df$Col2=="112770",]$High.School<-"Treutlen Middle/High School"
			df[df$Col2=="111777",]$High.School<-"Troup County High School"
			df[df$Col2=="111710",]$High.School<-"Twiggs County High School"
			df[df$Col2=="112043",]$High.School<-"Union Grove High"
			df[df$Col2=="113105",]$High.School<-"Vidalia Comprehensive High School"
			df[df$Col2=="110142",]$High.School<-"Booker T. Washington High School - Banking, Finance and Investment Small Sc"
			df[df$Col2=="112437",]$High.School<-"Webster County High School"
			df[df$Col2=="110048",]$High.School<-"Westover High School"
			df[df$Col2=="110971",]$High.School<-"Whitfield County Career Academy"
			df[df$Col2=="112555",]$High.School<-"Wilcox County High School"
			df[df$Col2=="110835",]$High.School<-"Spencer High School"
			df[df$Col2=="111970",]$High.School<-"William S. Hutchings Career Center"
			df[df$High.School=="A Z Kelsey Academy",]$High.School<-"AZ Kelsey Academy"
			df[df$High.School=="Alonzo A Crim High School",]$High.School<-"Crim High School"
			df[df$High.School=="Baker County High School",]$High.School<-"Baker County K12 School"
			df[df$High.School=="Berrien Academy Charter School",]$High.School<-"Berrien Academy Performance Learning Center"
			df[df$High.School=="Classic City Performance Learning Center",]$High.School<-"Classic City High School"
			df[df$High.School=="Coffee High School",]$High.School<-"Coffee County High School"
			df[df$High.School=="Early College Academy of Columbus",]$High.School<-"Early College Academy of Columbus at Waverly Terrace"
			df[df$High.School=="Frank McClarin High School",]$High.School<-"McClarin Alternative School"
			df[df$High.School=="Gateway to College Academy of Georgia Perimeter Co",]$High.School<-"Gateway to College Academy"
			df[df$High.School=="Heard County High School",]$High.School<-"New Heard County High School"
			df[df$High.School=="Hephzibah Comprehensive High School",]$High.School<-"Hephzibah High School"
			df[df$High.School=="Ivy Preparatory Academy - Gwinnett",]$High.School<-"Ivy Preparatory Academy School"
			df[df$High.School=="KIPP Atlanta Collegiate High School",]$High.School<-"KIPP Atlanta Collegiate"
			df[df$High.School=="Mountain Creek Academy",]$High.School<-"Mountain Creek Academy School"
			df[df$High.School=="South Atlanta School of Computer Animation and Des",]$High.School<-"South Atlanta School of Computer Animation and Design"
			df[df$High.School=="Southeast Bulloch High School",]$High.School<-"New Southeast Bulloch High School"
			df[df$High.School=="The Best Academy at Benjamin S. Carson High School",]$High.School<-"The Best Academy High School at Benjamin S. Carson"
			df[df$High.School=="Woody Gap High School",]$High.School<-"Woody Gap High/Elementary School"
			df[df$High.School=="Woodville Tompkins Technical And Career High Schoo",]$High.School<-"Woodville-Tompkins Technical and Career High School"
			df
			}